apiVersion: v1
kind: Pod
metadata:
  name: todoapp-1
  namespace: todoapp
  labels:
    app: todolist
spec:
  containers:
  - name: todoapp-container
    image: vitsheo/todoapp:3.0.0
    ports:
    - containerPort: 8000
    env:
    - name: PYTHONUNBUFFERED
      value: "1"
    - name: PYTHONDONTWRITEBYTECODE
      value: "1"

---
apiVersion: v1
kind: Pod
metadata:
  name: todoapp-2
  namespace: todoapp
  labels:
    app: todolist
spec:
  containers:
  - name: todoapp-container
    image: vitsheo/todoapp:3.0.0
    ports:
    - containerPort: 8000
    env:
    - name: PYTHONUNBUFFERED
      value: "1"
    - name: PYTHONDONTWRITEBYTECODE
      value: "1"
